### ISSUE TITLE
Cannot build master

### ISSUE THREAD

**Issue by andig** [NatelEnergy/grafana-plotly-panel#59]
Missing dependency?

	~/htdocs/grafana-plotly-panel master*
	❯ npm i
	audited 32130 packages in 9.316s
	found 4 moderate severity vulnerabilities
	  run `npm audit fix` to fix them, or `npm audit` for details

	~/htdocs/grafana-plotly-panel master* 10s
	❯ npm run-script build

	> natel-plotly-panel@0.0.6-dev build /Users/andig/htdocs/grafana-plotly-panel
	> webpack --config webpack.config.prod.js

	/Users/andig/htdocs/grafana-plotly-panel/node_modules/webpack-cli/bin/cli.js:235
	                                throw err;
	                                ^

	Error: Cannot find module 'uglifyjs-webpack-plugin'
	    at Function.Module._resolveFilename (module.js:548:15)
	    at Function.Module._load (module.js:475:25)
	    at Module.require (module.js:597:17)
	    at require (/Users/andig/htdocs/grafana-plotly-panel/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
	    at Object.<anonymous> (/Users/andig/htdocs/grafana-plotly-panel/webpack.config.prod.js:3:24)
	    at Module._compile (/Users/andig/htdocs/grafana-plotly-panel/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
	    at Object.Module._extensions..js (module.js:664:10)
	    at Module.load (module.js:566:32)
	    at tryModuleLoad (module.js:506:12)
	    at Function.Module._load (module.js:498:3)
	    at Module.require (module.js:597:17)
	    at require (/Users/andig/htdocs/grafana-plotly-panel/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
	    at WEBPACK_OPTIONS (/Users/andig/htdocs/grafana-plotly-panel/node_modules/webpack-cli/bin/convert-argv.js:115:13)
	    at requireConfig (/Users/andig/htdocs/grafana-plotly-panel/node_modules/webpack-cli/bin/convert-argv.js:117:6)
	    at /Users/andig/htdocs/grafana-plotly-panel/node_modules/webpack-cli/bin/convert-argv.js:124:17
	    at Array.forEach (<anonymous>)
	    at module.exports (/Users/andig/htdocs/grafana-plotly-panel/node_modules/webpack-cli/bin/convert-argv.js:122:15)
	    at yargs.parse (/Users/andig/htdocs/grafana-plotly-panel/node_modules/webpack-cli/bin/cli.js:232:39)
	    at Object.parse (/Users/andig/htdocs/grafana-plotly-panel/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
	    at /Users/andig/htdocs/grafana-plotly-panel/node_modules/webpack-cli/bin/cli.js:210:8
	    at Object.<anonymous> (/Users/andig/htdocs/grafana-plotly-panel/node_modules/webpack-cli/bin/cli.js:500:3)
	    at Module._compile (module.js:653:30)
	    at Object.Module._extensions..js (module.js:664:10)
	    at Module.load (module.js:566:32)
	    at tryModuleLoad (module.js:506:12)
	    at Function.Module._load (module.js:498:3)
	    at Module.require (module.js:597:17)
	    at require (internal/module.js:11:18)
	    at Object.<anonymous> (/Users/andig/htdocs/grafana-plotly-panel/node_modules/webpack/bin/webpack.js:155:2)
	    at Module._compile (module.js:653:30)
	    at Object.Module._extensions..js (module.js:664:10)
	    at Module.load (module.js:566:32)
	    at tryModuleLoad (module.js:506:12)
	    at Function.Module._load (module.js:498:3)
	    at Function.Module.runMain (module.js:694:10)
	    at startup (bootstrap_node.js:204:16)
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! natel-plotly-panel@0.0.6-dev build: `webpack --config webpack.config.prod.js`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the natel-plotly-panel@0.0.6-dev build script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /Users/andig/.npm/_logs/2019-01-12T09_40_43_437Z-debug.log

**Comment by ryantxu** [comment]
yup.  fixed in master:

https://circleci.com/gh/NatelEnergy/grafana-plotly-panel/76
